- _pages/clearance-process/index.md
The numbered list at the top should be axed and Christine's map should go there.
> Content to use on the process

- _data/navigation.yml
- _pages/about/index.md
- _pages/clearance-process/index.md
- terms.json
More info about the PRA that testers may miss on the homepage. updated side nav too
> content add

- _data/terms.json
Fixed PII here too. 
Sorry for the separate PR, I'm not sophisticated enough to add this the previous PR. Issue #31
> Fixed identifiable (was identifying) in PII 

- _pages/index.md
Issue #31 
(Yes, I know this text might get replaced, but I wanted to do the simplest possible PR from an issue.)
> Fix identifiable (from identifying) in PII

- _data/navigation.yml
@qmanderson1 per our chat this morning started reordering the nav. Is this the right order?
> reordering topnav

- _data/navigation.yml
- _pages/burden/activities.md
- _pages/burden/estimation.md
- _pages/burden/index.md
resolves #59 
In this PR:
* Adds 2 new sub pages for Estimating Burden
* Updates url path from `/estimating-burden` >> `/burden`
> adding burden subpages

- _pages/contact/index.md
Added a bulleted list of when not to contact OIRA.
> Contact Update

- _layouts/home.html
- _pages/index.md
Updated homepage including:
* task-based prompts rather than "about the pra" prompts. 
* added links
> updating homepage with task-based CTAs, adding links

- _pages/do-i-need-clearance/pra-and-the-internet.md
From Amanda's google doc. Minor note, I changed IRS' to IRS's in line with their site.
> Initial load of PRA and Web content

- _pages/additional-resources/examples.md
- _pages/additional-resources/training.md
- _pages/clearance-process/supporting-statement.md
- _pages/clearance-types/examples-of-how-to-make-the-right-clearance-decision.md
- _pages/clearance-types/what-type-of-clearance-applies-to-my-request.md
* remove subpages from additional resources and clearance types
* add new page for supporting statement
> Remove subpages and add new supporting statement 

- _pages/additional-resources/index.md
Additional resources populated with 6 PRA related documents
> Additional Resources Populated

- _pages/burden/estimation.md
Added in content, and an external link. Still needs internal content linking.
> Burden Estimate content

- _pages/burden/activities.md
> Added content

- _pages/clearance-process/supporting-statement.md
This is the bulk of the content about supporting statements; missing is the plain language desc of the 18 questions, which I'd like to ask about in the call tomorrow (or have a phone chat with Nick to clear up)
> Content upload

- _pages/burden/index.md
I think that link is borked on line 22! Also, still a missing link on line 35; need to add supp statement page
> Added page content

- _pages/burden/activities.md
- _pages/burden/estimation.md
fixing double headlines on some new pages
> removing double h1s on burden section

- _pages/contact/index.md
> fixing-link

- _pages/clearance-types/index.md
Clearance types content added, with working links!
> Add content

- _pages/about/index.md
Realized this is only coming from notes from chats with desk officers, can follow up with Nick.
> Added in the "what happens if I don't comply" text

- _pages/about/index.md
- highlighted the contagion of legal challenge
- attempted to unpack the language from "revoked" and "expired" to "they'll make you stop."
> Another stab at the consequences of failure

- _pages/clearance-types/index.md
> Added clearance types anchors

- _pages/github-training/profile5.md
Changed profile name and added short description.
> Sharon Mar Profile

- _pages/github-training/profile4.md
I personalized the MM User Profile
> Personalizing MM Profile

- _pages/clearance-process/supporting-statement.md
I looked through other documents. Looks like Supporting Statement is normally capitalized, so I've gone with that!
> Capitalization of "supporting statement"

- _includes/scripts.html
Adds DAP code to the footer of all pages.
> Add DAP tracking code

- .circleci/config.yml
- Gemfile
This will allow for basic HTML tests.
> Add htmlproofer

- _data/contacts.json
Integrating more information received during the week.
> Added DOI and NCUA information

- _data/contacts.json
- _includes/contacts.html
- _js/contacts.js
- _pages/contact/index.md
- _scss/_uswds-theme-custom-styles.scss
- _scss/components/_contacts.scss
- package-lock.json
- package.json
Functionality to search for agencies contact information using underlying `contacts.json` data file. 
Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/pra.gov/bh-contact-search/contact/#help-submitting-an-information-request
Fixes https://github.com/GSA/pra.gov/issues/110
Fixes https://github.com/GSA/pra.gov/issues/43
> Agency contact lookup

- Gemfile
- Gemfile.lock
- _config.yml
- _includes/header.html
- _includes/scripts.html
- _layouts/search-results.html
Implement search using https://github.com/18F/jekyll_pages_api_search
> Add jekyll search

- _includes/footer.html
- _layouts/full.html
- _layouts/search-results.html
- _pages/contact/index.md
- _pages/privacy.md
Add privacy policy based on plainlanguage.gov.
Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/pra.gov/bh-privacy-policy/privacy/
> Add privacy policy

- _pages/do-i-need-clearance/index.md
> Content update

- _pages/burden/estimation.md
Added link to HHS burden calculator in-line
> HHS Burden Calc link

- _pages/about/index.md
Corrected: personally identifying information 
Now: personally identifiable information
> Fixed typo

- _data/terms.json
- Added approved content from OMBGC
- Closes issues #174, #175, #178, #179, #186, #187, #193, #194
> Final content added

- _pages/do-i-need-clearance/form-updates-and-conversions.md
Content approved by OMBGC. 
Closes issue #179
> Added final content

- _data/terms.json
- _pages/about/index.md
- _pages/burden/estimation.md
- _pages/burden/index.md
- _pages/clearance-process/index.md
- _pages/clearance-process/supporting-statement.md
- _pages/clearance-types/index.md
- _pages/contact/index.md
- _pages/do-i-need-clearance/form-updates-and-conversions.md
- _pages/do-i-need-clearance/index.md
- _pages/do-i-need-clearance/pra-and-the-internet.md
All content updates from OMB general counsel are reflected in this pull request, as well as edits from @ToniBonittoGS, including correcting header hierarchies.
> Content approved by OMBGC

- _includes/demo.html
- _layouts/default.html
- _pages/about/index.md
- _scss/_uswds-theme-color.scss
- _scss/_uswds-theme-custom-styles.scss
- _scss/components/_banner.scss
- _scss/components/_demo.scss
- package-lock.json
This is a banner that will appear on the site while it is in BETA on the demo URL.
Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/demo-banner/
> Demo banner

- _data/terms.json
- _pages/additional-resources/index.md
- _pages/clearance-process/index.md
- _pages/clearance-types/index.md
Small language edits. Including resolving issues #207 
Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/mmcmanusOMB-patch-1/about/
> Pre-Demo Patch

- _data/contacts.json
- _pages/clearance-process/index.md
- _pages/contact/index.md
This addresses three pending issues as a means of promoting more github familiarity
> Pre launch edits

- _includes/demo.html
- _includes/footer.html
- _scss/components/_demo.scss
**Based on the discussion here:** https://github.com/GSA/digitalgov-pra/issues/219
This addresses the first two items in this comment: https://github.com/GSA/digitalgov-pra/issues/219#issuecomment-499882551
- Update the language in the current header to say "email us feedback" and go to a mailto link directly.
- Update the feedback text in the footer
**Preview:** https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/digitalgov-pra/feedback-edits/
> Edits to Feedback language

- _data/contacts.json
- _pages/additional-resources/index.md
Moving ROCIS link, noting it is a login only, and added the DHS contact. #248 #244
> Launch day patch

- _pages/about/index.md
- _pages/clearance-process/index.md
> Typo squash

- _scss/components/_banner.scss
Fixing https://github.com/GSA/digitalgov-pra/issues/227 via @cmajel and @ToniBonittoGSA 
**Preview:** https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/digitalgov-pra/fix-gov-banner/
> fixing color of gov banner

- _pages/privacy.md
> Typos in privacy policy

- _pages/do-i-need-clearance/index.md
Adding Foreign Nationals as part of the "public." Language has been approved.
> Add Foreign Nationals

- .broswerslistrc
- _config.yml
- gulpfile.js
Changes: 
- add `url` parameter to `config.yml` for the `jekyll-sitemap` to work
- update uswds-gulp configuration
> Fix sitemap

- _includes/scripts.html
* add TTS as subagency in DAP script
`&subagency=TTS`
> Add subagency to dap code

- _scss/_uswds-theme-color.scss
- _scss/_uswds-theme-components.scss
- _scss/components/_header.scss
- _scss/components/_sidenav.scss
- _scss/components/_typography.scss
- gulpfile.js
- package-lock.json
- package.json
- Updated SASS task in gulpfile
- Updated uswds-gulp 
- Removed quotes from custom styles that used USWDS utils
- Update custom identifier settings
- Add custom reverse link color settings
> Updates for uswds 2.9.0 upgrade.

- _pages/additional-resources/index.md
Fixing links and adding updated memo.
> Fixing links

- _includes/google-analytics.html
> Update to Google Analytics 4

- package-lock.json
> POAM May Updates

- _data/terms.json
Added revision request, extension request, and reinstatement request to pra.digital.gov glossary, per OMB request.
**Preview**
[Link to Preview](#)
> Added three terms to pra.digital.gov glossary

- .circleci/config.yml
- assets/uswds/js/bundle.js
- package.json
Adds javascript compilation to build steps for `federalist` and `circleci`.
This will update the glossary terms when `_data/terms.json` is edited.
Updates glossary terms for #379
> Add js compilation to build step, update terms glossary

- assets/uswds/js/uswds.js
This "Fix" breaks styles on the PRA site. 
The issue the PR resolves is not a serious issue at this time.
Reverts GSA/digitalgov-pra#384
> Revert "Fix code scanning alert no. 1: Incomplete string escaping or encoding"

- _data/contacts.json
- _data/terms.json
- _pages/additional-resources/index.md
- _pages/do-i-need-clearance/index.md
Primary purpose is to include the new Usability Testing guidance as an additional resources and in our "does it need clearance " page. Also updated some links and contact information.
> [!NOTE]
> [Original PR](https://github.com/GSA/digitalgov-pra/pull/394) had a misnamed branch that caused a build to not complete
> Updating contacts and added Usability testing V2

- _includes/google-analytics.html
> Update google-analytics.html tag manager update
